apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-goconfig
rules:
- apiGroups: [""]
  resources: ["configmaps", "namespaces"]
  verbs: ["get", "list", "create", "update"]